name: build_pdf

on: push

# on: 
#   push:
#     branches:
#       - main

jobs:
  render_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: typst-community/setup-typst@v3
      - name: build
        run: |
          git submodule update --init --recursive
          make build

      - name: Checkout output branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout --orphan output
          git rm -r --cached .
          git add -f *.pdf
          git commit -m "Update output files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true